### PR TITLE
Fixed issue with IsExternalInit must be declared for all TFMs.

### LINKED ISSUE #5: IsExternalInit must be declared for all TFMs
Unlike other polyfill packages where you can get away with declaring attributes only where the TFM does not declare them, `IsExternalInit` *must* be declared in the same assembly forever and for all TFMs or else it's a binary breaking change.

I see in your nuspec that you omit the declaration for net5 but you can't do that. You must declare it there as well.
The reason being the compiler generates metadata on the `init` property accessors that references this attribute using its assembly-qualified type name. When other assemblies reference this one and invoke an `init` accessor, the compiler embeds that exact same assembly-qualified reference into their invocation of that accessor. Now imagine this referencing library runs in a process where the referenced library is no longer the one that targeted net472 but targets net5. The CLR will throw a MissingMethodException when it encounters the init accessor because the attribute on the accessor does not match the IsExternalInit reference in the caller.

[See proof of the breaking change](https://1drv.ms/u/s!Aj3kll8mDD0GgajMRHP5_lERdRQ8Tb4?e=iJIWCH)

### PR DESCRIPTION
**Pull request by AraHaan**
Fixes #5.

### CODE REVIEW

File: src/IsExternalInit/IsExternalInit.cs [hunk 1]
```diff
@@ -36,7 +36,6 @@
 // SOFTWARE.
 #endregion
 
-#if !ISEXTERNALINIT_DISABLE
```
Comment (manuelroemer) [inline src/IsExternalInit/IsExternalInit.cs:39]: Can we keep this constant? Removing it could be a breaking change (e.g. for a project setup which references the package globally in a `Directory.Build.props` and then excludes the attribute in selected sub-projects which only ever targeted .NET >= 5).

File: src/IsExternalInit.nuspec [hunk 2]
```diff
@@ -47,16 +47,23 @@ Please see https://github.com/manuelroemer/IsExternalInit for additional informa
...
 
-    <!-- >= .NET 5 supports IsExternalInit. -->
-    <file src="../../src/.nuget/_._" target="contentFiles/cs/net5.0"/>
-    <file src="../../src/.nuget/_._" target="content/net5.0"/>
+    <!--
+    >= .NET 5 requires IsExternalInit to be included per project.
+
+    See issue: https://github.com/manuelroemer/IsExternalInit/issues/5 for more details.
+    -->
+    <file src="ExcludeFromCodeCoverage/IsExternalInit.cs.pp" target="contentFiles/cs/net5.0/IsExternalInit/IsExternalInit.cs.pp"/>
```
Comment (manuelroemer) [inline src/IsExternalInit.nuspec:55]: I think we can remove the `net5.0` folder(s) altogether since the `netstandard2.0` targets below will automatically include everything >= .NET 5 anyway. Or am I missing something here?

**Review by manuelroemer — COMMENTED** [review]
Hey, thanks a lot for creating a fix so quickly. Much appreciated! 🚀 

I've only got two comments. If you don't want to address these yourself you can also just @ me, then I'll address them before pushing a new version on NuGet.

File: src/IsExternalInit/IsExternalInit.cs (hunk 1 above)
Comment (AraHaan) [reply src/IsExternalInit/IsExternalInit.cs:39]: Migration should be easy as MSBuild is on their side all they got to do is add this to their ``PackageReference`` then:

``Condition="'$(ISEXTERNALINIT_DISABLE)' != '' AND '$(ISEXTERNALINIT_DISABLE)' == 'false'"`` and then it should work like normally. 👍 You then would have to warn them to do that however so then it won't affect them much plus then it does the same and changes it to an msbuild property instead of something they should add to ``DefineConstant``s on the project. However I think a note saying that they would need to change their csproj is ok and minimal change on their end too as long as they know *what* to change.

**Comment by AraHaan** [comment]
@manuelroemer it should be ready now.

**Comment by manuelroemer** [comment]
My apologies for taking so long with this - I had so many other things to do IRL/with my job that I was honestly lacking the required motivation to follow up here.

Again, thank you so much for making the changes! 🍻 
 I'll do a last test locally and then see that it lands on NuGet this evening!
